### PR TITLE
Fix issue 81

### LINKED ISSUE #81: Refactor into a function that accepts 'askForConfirmation' parameter
https://github.com/RedHatInsights/insights-operator-cli/blob/fcfd553c4239af1b191dce01f565945a8c45f67b/commands/profiles.go#L57

please see:
https://github.com/RedHatInsights/insights-operator-cli/blob/fcfd553c4239af1b191dce01f565945a8c45f67b/commands/clusters.go#L41

https://github.com/RedHatInsights/insights-operator-cli/blob/fcfd553c4239af1b191dce01f565945a8c45f67b/commands/clusters.go#L47

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Refactoring implementation of command 'delete profile' so it is possible to call it w/o confirmation.

Fixes #81 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactor (refactoring code, removing useless files)

## Testing steps
This change is backed by new unit tests, so `./test.sh` is all what's needed ATM.

### CODE REVIEW

File: ioc.go [hunk 1]
```diff
@@ -193,7 +194,7 @@ func executeFixedCommand(t string) {
 		commands.DeleteClusterConfiguration(api, configuration)
 	case "delete profile":
 		profile := prompt.Input("profile: ", commands.LoginCompleter)
-		commands.DeleteConfigurationProfile(api, profile)
+		commands.DeleteConfigurationProfile(api, profile, *askForConfirmation)
```
Comment (bond95) [inline ioc.go]: I don't see where `askForConfirmation` is set.
